#!/usr/bin/env bash
# Gracefully reloads Gunicorn by sending the HUP signal to the master process.

# Get the PID of the Gunicorn master process
MASTER_PID=$(pgrep -f 'gunicorn.*--bind' | head -n 1)

# Send the HUP signal to the Gunicorn master process
if [ -n "$MASTER_PID" ]; then
  kill -HUP $MASTER_PID
fi
